/**
 * Auto-Generated SSC CGL Paper Loader
 * 
 * This file will be auto-generated by the generate-loader.ps1 script
 * Run: npm run generate-loader
 */

import { SSCCGLService } from '../services/ssc-cgl-service';
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';

interface PaperFile {
  id: string;
  fileName: string;
  displayName: string;
  hasAnswers: boolean;
}

// This will be auto-generated
const PAPER_FILES: PaperFile[] = [];

/**
 * Load all SSC CGL papers from the data folders
 */
export async function loadAllSSCCGLPapers(): Promise<{
  loaded: number;
  failed: number;
  errors: string[];
}> {
  const service = SSCCGLService.getInstance();
  const results = {
    loaded: 0,
    failed: 0,
    errors: [] as string[],
  };

  console.log(`📚 Loading ${PAPER_FILES.length} SSC CGL papers...`);

  for (const paper of PAPER_FILES) {
    try {
      // Load paper data
      const paperPath = `../../SSC_CGL/${paper.fileName}`;
      const paperData = require(paperPath);

      // Try to load answers if available
      let answersData = null;
      if (paper.hasAnswers) {
        try {
          const answersPath = `../../ai_generated_answers/${paper.fileName}`;
          answersData = require(answersPath);
        } catch (error) {
          console.warn(`⚠️  Answers not found for ${paper.displayName}`);
        }
      }

      // Load into service
      await service.loadPaper(paper.id, paperData, answersData);
      results.loaded++;

      if (results.loaded % 25 === 0) {
        console.log(`✅ Progress: ${results.loaded}/${PAPER_FILES.length} papers loaded`);
      }
    } catch (error) {
      results.failed++;
      const errorMsg = `Failed to load ${paper.displayName}: ${error}`;
      results.errors.push(errorMsg);
      console.error(`❌ ${errorMsg}`);
    }
  }

  console.log(`
🎉 Loading Complete!
✅ Loaded: ${results.loaded}
❌ Failed: ${results.failed}
  `);

  return results;
}

/**
 * Load papers in smaller batches to improve performance
 */
export async function loadPapersInBatches(
  batchSize: number = 25,
  onProgress?: (loaded: number, total: number) => void
): Promise<void> {
  const service = SSCCGLService.getInstance();
  const total = PAPER_FILES.length;

  for (let i = 0; i < total; i += batchSize) {
    const batch = PAPER_FILES.slice(i, i + batchSize);
    
    await Promise.all(
      batch.map(async (paper) => {
        try {
          const paperData = require(`../../SSC_CGL/${paper.fileName}`);
          let answersData = null;
          
          if (paper.hasAnswers) {
            try {
              answersData = require(`../../ai_generated_answers/${paper.fileName}`);
            } catch {
              // No answers
            }
          }
          
          await service.loadPaper(paper.id, paperData, answersData);
        } catch (error) {
          console.error(`Failed: ${paper.displayName}`);
        }
      })
    );

    const loaded = Math.min(i + batchSize, total);
    if (onProgress) {
      onProgress(loaded, total);
    }
    console.log(`📦 Batch complete: ${loaded}/${total}`);
  }
}

/**
 * Get total paper count
 */
export function getTotalPaperCount(): number {
  return PAPER_FILES.length;
}

/**
 * Get papers by year
 */
export function getPapersByYear(year: number): PaperFile[] {
  return PAPER_FILES.filter(p => 
    p.displayName.includes(`CGL ${year}`) || 
    p.displayName.includes(`${year}`)
  );
}
