# Generate SSC CGL Paper Loader
# This script scans the SSC_CGL and ai_generated_answers folders
# and generates a TypeScript loader file

Write-Host "🚀 SSC CGL Paper Loader Generator" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""

# Paths
$sscFolder = "C:\Users\aloo\exam-ai\SSC_CGL"
$answersFolder = "C:\Users\aloo\exam-ai\ai_generated_answers"
$outputFile = "C:\Users\aloo\exam-ai\project\scripts\generated-loader.ts"

# Get all paper files (excluding FAILED ones)
Write-Host "📁 Scanning SSC_CGL folder..." -ForegroundColor Yellow
$paperFiles = Get-ChildItem -Path $sscFolder -Filter "*.json" | Where-Object { 
    $_.Name -notlike "*_FAILED*" 
}

Write-Host "   Found $($paperFiles.Count) papers" -ForegroundColor Green

# Get all answer files (excluding FAILED ones)
Write-Host "📁 Scanning ai_generated_answers folder..." -ForegroundColor Yellow
$answerFiles = Get-ChildItem -Path $answersFolder -Filter "*.json" | Where-Object { 
    $_.Name -notlike "*_FAILED*" 
}
Write-Host "   Found $($answerFiles.Count) answer files" -ForegroundColor Green
Write-Host ""

# Build answer lookup
$answerLookup = @{}
foreach ($file in $answerFiles) {
    $answerLookup[$file.Name] = $true
}

# Process papers
$papers = @()
foreach ($file in $paperFiles) {
    $fileName = $file.Name
    $baseName = $file.BaseName
    
    # Extract ID from filename (after last __)
    if ($baseName -match '__([a-f0-9]+)$') {
        $id = $matches[1]
        $displayName = ($baseName -replace '__[a-f0-9]+$', '') -replace '_', ' '
        $hasAnswers = $answerLookup.ContainsKey($fileName)
        
        $papers += [PSCustomObject]@{
            Id = $id
            FileName = $fileName
            DisplayName = $displayName
            HasAnswers = $hasAnswers
        }
    }
}

Write-Host "✅ Processed $($papers.Count) papers" -ForegroundColor Green
Write-Host ""

# Generate TypeScript code
Write-Host "📝 Generating TypeScript loader..." -ForegroundColor Yellow

$tsCode = @"
/**
 * AUTO-GENERATED SSC CGL Paper Loader
 * Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
 * Total Papers: $($papers.Count)
 * Papers with AI Answers: $(($papers | Where-Object { $_.HasAnswers }).Count)
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: powershell .\generate-loader.ps1
 */

import { SSCCGLService } from '../services/ssc-cgl-service';

interface PaperFile {
  id: string;
  fileName: string;
  displayName: string;
  hasAnswers: boolean;
}

/**
 * All available SSC CGL papers
 */
export const PAPER_FILES: PaperFile[] = [
"@

# Add each paper
foreach ($paper in $papers) {
    $displayName = $paper.DisplayName.Replace("'", "\'")
    $hasAnswers = if ($paper.HasAnswers) { 'true' } else { 'false' }
    
    $tsCode += "`n  {`n"
    $tsCode += "    id: '$($paper.Id)',`n"
    $tsCode += "    fileName: '$($paper.FileName)',`n"
    $tsCode += "    displayName: '$displayName',`n"
    $tsCode += "    hasAnswers: $hasAnswers,`n"
    $tsCode += "  },"
}

$tsCode += @"

];

/**
 * Load all SSC CGL papers into the service
 */
export async function loadAllSSCCGLPapers(): Promise<{
  loaded: number;
  failed: number;
  errors: string[];
}> {
  const service = SSCCGLService.getInstance();
  const results = {
    loaded: 0,
    failed: 0,
    errors: [] as string[],
  };

  console.log('📚 Loading ' + PAPER_FILES.length + ' SSC CGL papers...');

  for (const paper of PAPER_FILES) {
    try {
      // Dynamically import paper
      const paperModule = await import('../../SSC_CGL/' + paper.fileName);
      const paperData = paperModule.default || paperModule;

      // Try to load answers
      let answersData = null;
      if (paper.hasAnswers) {
        try {
          const answersModule = await import('../../ai_generated_answers/' + paper.fileName);
          answersData = answersModule.default || answersModule;
        } catch (error) {
          console.warn('⚠️  Answers not found for ' + paper.displayName);
        }
      }

      // Load into service
      await service.loadPaper(paper.id, paperData, answersData);
      results.loaded++;

      if (results.loaded % 25 === 0) {
        console.log('✅ Progress: ' + results.loaded + '/' + PAPER_FILES.length + ' papers loaded');
      }
    } catch (error) {
      results.failed++;
      const errorMsg = 'Failed to load ' + paper.displayName + ': ' + error;
      results.errors.push(errorMsg);
      console.error('❌ ' + errorMsg);
    }
  }

  console.log('🎉 Loading Complete! ✅ Loaded: ' + results.loaded + ' ❌ Failed: ' + results.failed);

  return results;
}

/**
 * Load papers in batches for better performance
 */
export async function loadPapersInBatches(
  batchSize: number = 25,
  onProgress?: (loaded: number, total: number) => void
): Promise<void> {
  const service = SSCCGLService.getInstance();
  const total = PAPER_FILES.length;

  for (let i = 0; i < total; i += batchSize) {
    const batch = PAPER_FILES.slice(i, i + batchSize);
    
    await Promise.all(
      batch.map(async (paper) => {
        try {
          const paperModule = await import('../../SSC_CGL/' + paper.fileName);
          const paperData = paperModule.default || paperModule;
          
          let answersData = null;
          if (paper.hasAnswers) {
            try {
              const answersModule = await import('../../ai_generated_answers/' + paper.fileName);
              answersData = answersModule.default || answersModule;
            } catch {
              // No answers
            }
          }
          
          await service.loadPaper(paper.id, paperData, answersData);
        } catch (error) {
          console.error('Failed: ' + paper.displayName);
        }
      })
    );

    const loaded = Math.min(i + batchSize, total);
    if (onProgress) {
      onProgress(loaded, total);
    }
  }
}

/**
 * Load only papers from a specific year
 */
export async function loadPapersByYear(year: number): Promise<number> {
  const service = SSCCGLService.getInstance();
  const yearPapers = PAPER_FILES.filter(p => 
    p.displayName.includes('CGL ' + year) || p.displayName.includes(' ' + year + ' ')
  );

  let loaded = 0;
  for (const paper of yearPapers) {
    try {
      const paperModule = await import('../../SSC_CGL/' + paper.fileName);
      const paperData = paperModule.default || paperModule;
      
      let answersData = null;
      if (paper.hasAnswers) {
        try {
          const answersModule = await import('../../ai_generated_answers/' + paper.fileName);
          answersData = answersModule.default || answersModule;
        } catch {}
      }
      
      await service.loadPaper(paper.id, paperData, answersData);
      loaded++;
    } catch (error) {
      console.error('Failed to load ' + paper.displayName);
    }
  }

  console.log('✅ Loaded ' + loaded + ' papers from year ' + year);
  return loaded;
}

/**
 * Get statistics about available papers
 */
export function getPaperStats() {
  const stats = {
    total: PAPER_FILES.length,
    withAnswers: PAPER_FILES.filter(p => p.hasAnswers).length,
    byYear: {} as Record<number, number>,
  };

  // Count by year
  PAPER_FILES.forEach(paper => {
    const yearMatch = paper.displayName.match(/(\d{4})/);
    if (yearMatch) {
      const year = parseInt(yearMatch[1]);
      stats.byYear[year] = (stats.byYear[year] || 0) + 1;
    }
  });

  return stats;
}

/**
 * Search for papers by name
 */
export function searchPapers(query: string): PaperFile[] {
  const lowerQuery = query.toLowerCase();
  return PAPER_FILES.filter(p => 
    p.displayName.toLowerCase().includes(lowerQuery)
  );
}

// Export total count
export const TOTAL_PAPERS = PAPER_FILES.length;
export const PAPERS_WITH_ANSWERS = PAPER_FILES.filter(p => p.hasAnswers).length;
"@

# Save to file
$tsCode | Out-File -FilePath $outputFile -Encoding UTF8 -Force

Write-Host "✅ Generated: $outputFile" -ForegroundColor Green
Write-Host ""
Write-Host "📊 Statistics:" -ForegroundColor Cyan
Write-Host "   Total Papers: $($papers.Count)" -ForegroundColor White
Write-Host "   With Answers: $(($papers | Where-Object { $_.HasAnswers }).Count)" -ForegroundColor White
Write-Host "   Without Answers: $(($papers | Where-Object { -not $_.HasAnswers }).Count)" -ForegroundColor White
Write-Host ""
Write-Host "📚 Papers by Year:" -ForegroundColor Cyan
$papers | Group-Object { 
    if ($_.DisplayName -match '(\d{4})') { $matches[1] } else { 'Unknown' }
} | Sort-Object Name | ForEach-Object {
    Write-Host "   $($_.Name): $($_.Count) papers" -ForegroundColor White
}
Write-Host ""
Write-Host "🎉 Done! Import the loader in your app:" -ForegroundColor Green
Write-Host ""
Write-Host "   import { loadAllSSCCGLPapers } from './scripts/generated-loader';" -ForegroundColor Yellow
Write-Host "   await loadAllSSCCGLPapers();" -ForegroundColor Yellow
Write-Host ""
